apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-lb
spec:
  type: LoadBalancer
  sessionAffinity: None
  selector:
    app: controlcenter
  ports:
  - name: kafka-ui-lb
    port: 9021
    protocol: TCP
    targetPort: 9021
